apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rotina-db
  namespace: rotina
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
